### ISSUE TITLE
Implemenet improvements to a cooperation algorithm

### ISSUE THREAD

**Issue by unbalancedparentheses** [lambdaclass/finance_playground#77]
@ole-peters: "One idea for playful research: our cooperation algorithm is fun, and @adlightner made some suggestions, in his peer-review, for extending that research. For example, thinking about freeloaders, cooperation costs etc. Manuscript and review are here: https://www.researchers.one/article/2019-03-4"

**Comment by ole-peters** [comment]
Feel free to copy the code from researchers.one - there's a supplementary file, which you should be able to see. You can add that to the notebook as a starting point.

**Comment by unbalancedparentheses** [comment]
Awesome. We will do that with @metdinov.

**Comment by ole-peters** [comment]
Also, get in touch with @trishankkarthik who reproduced the figure in Peters & Gell-Mann 2016, here 

https://github.com/trishankkarthik/notebooks/blob/master/Evaluating%20Gambles%20using%20Dynamics.ipynb

**Comment by trishankkarthik** [comment]
Thanks, Ole!

You are free to steal my code
